AllCops:
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 2.4

Layout/EndOfLine:
  EnforcedStyle: lf
Layout/LineLength:
  Enabled: false
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'configure']
Style/FormatStringToken:
  EnforcedStyle: template
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
Lint/EmptyFile:
  Enabled: false
