#!/bin/bash
# Personal bash completeion for in project commands

_comp_dotfiles() {
  if [ "${#COMP_WORDS[@]}" != "2" ]; then
    return
  fi
  local opts="$(awk '/case \$INSTALL_TYPE/{flag=1;next}/esac/{flag=0}flag' $(which dotfiles-update) | grep [a-z]\) | sed 's/\(.*\)).*/\1/g' | tr -s '\n' ' ')"
  COMPREPLY=($(compgen -W "${opts}" "${COMP_WORDS[1]}"))
}

complete -F _comp_dotfiles dotfiles-update
