---
nvm:
  version: v0.39.1
  nodeVersions:
    - 18.20.4

pyenv:
  pythonVersion: 3.11.4
  extraPythonVersions:
    - 3.8.17

rvm:
  rubyVersion: 3.2.2
  extraRubiesVersions:
    - 2.7.3
    - 2.4.10

sdkman:
  javaVersions:
    - 11.0.12-open
    - 17.0.2-open
    - 21.0.7-tem
  groovyVersions:
    - 2.4.12
    - 2.4.21

terraform:
  tfenvVersion: 1.2.9
  tgenvVersion: 0.48.7

# Directories and files links to be create in $HOME. Use relative path.
dotfiles:
  dirs:
    - .config/nvim/undo
    - .config/nvim/tmp
    - .config/rubocop
    - .config/k9s
    - .bash_completion.d
    - tools
    - bin
  links:
    inputrc: .inputrc
    bin/db2con: bin/db2con
    bin/gradlew: bin/gradlew
    bin/ichatest: bin/ichatest
    bin/sgraph: bin/sgraph
    bin/groovylint: bin/groovylint
    bin/gentags: bin/gentags
    bin/erbvalidate: bin/erbvalidate
    nvim/init.lua: .config/nvim/init.lua
    nvim/syntax: .config/nvim/syntax
    nvim/minisnip: .config/nvim/minisnip
    nvim/scripts: .config/nvim/scripts
    nvim/spell: .config/nvim/spell
    nvim/lua: .config/nvim/lua
    nvim/after: .config/nvim/after
    mdlrc: .mdlrc
    markdownlint.yaml: markdownlint.yaml
    mdl_style.rb: .mdl_style.rb
    shellcheckrc: .shellcheckrc
    ctags.d: .ctags.d
    gitattributes: .gitattributes
    gitconfig: .gitconfig
    irbrc: .irbrc
    rvmrc: .rvmrc
    puppet-lint.rc: .puppet-lint.rc
    reek: .reek
    screenrc: .screenrc
    tmux.conf: .tmux.conf
    vintrc.yaml: .vintrc.yaml
    yamllint: .config/yamllint
    Pythonfile: Pythonfile
    package.json: package.json
    Gemfile: Gemfile
    rubocop.yml: .config/rubocop/config.yml
    codenarc.properties: .codenarc.properties
    gitexclude: .gitignore
    bash_completion: .bash_completion.d/bash_completion
    k9s/plugins.yaml: .config/k9s/plugins.yaml

systemPackages:
  - augeas-tools
  - bat
  - bash-completion
  - chromium
  - cpio
  - curl
  - colorized-logs
  - docker.io
  - dos2unix
  - dnsutils
  - fd-find
  - fuse
  - fzf
  - git
  - gh
  - golang
  - gpg
  - keychain
  - kubectl
  - kcat
  - lazygit
  - llvm
  - libssl-dev
  - liblzma-dev
  - libxml2-utils
  - lua5.3
  - make
  - man-db
  - ncat
  - ninja-build
  - nmap
  - openssh-client
  - oras
  - plantuml
  - postgresql
  - ripgrep
  - rpm
  - rpm2cpio
  - shellcheck
  - sshpass
  - sshuttle
  - tk-dev
  - tmux
  - tcpdump
  - universal-ctags
  - unzip
  - wget
  - xz-utils
  - zip

installReleaseTools:
  - hadolint/hadolint
  - derailed/k9s
  - mrjosh/helm-ls
  - terraform-linters/tflint
  - golangci/golangci-lint
  - artempyanykh/marksman
  - argoproj/argo-cd
