source 'https://rubygems.org'

gem 'bundler'
gem 'httpaprty'
gem 'mdl'
gem 'rubocop'
gem 'reek'
gem 'solargraph'
gem 'win32-dir'
gem 'win32-eventlog'
gem 'win32-process'
gem 'win32-security'
gem 'win32-service'
