# frozen_string_literal: true

source 'https://rubygems.org'

gem 'ast'
gem 'chef-utils', '15.17.4'
gem 'httparty'
gem 'mdl'
gem 'mixlib-shellout', '3.2.6'
gem 'nokogiri', '1.9.1'
gem 'parallel', '1.20.1'
gem 'reek'
gem 'rubocop', '0.93.1'
gem 'rubocop-ast', '1.4.1'
gem 'rubocop-rspec', '1.44.1'

gem 'puppet', '~> 5.5.22'
gem 'puppet-lint'
gem 'puppet-lint-absolute_classname-check', '~> 2.0.0'
gem 'puppet-lint-empty_string-check'
gem 'puppet-lint-leading_zero-check'
gem 'puppet-lint-resource_reference_syntax'
gem 'puppet-lint-top_scope_facts-check'
gem 'puppet-lint-trailing_comma-check'
gem 'puppet-lint-unquoted_string-check'
gem 'puppet-lint-version_comparison-check'
