require("paq") {
  { 'nvim-lua/plenary.nvim' },
  { 'savq/paq-nvim' },
  { 'andymass/vim-matchup' },
  { 'rcarriga/nvim-notify' },

  { 'nvim-telescope/telescope.nvim', branch = '0.1.x' },
  { 'nvim-telescope/telescope-fzf-native.nvim', build = 'make' },
  { 'nvim-telescope/telescope-ui-select.nvim' },

  { 'neovim/nvim-lspconfig' },
  { 'mason-org/mason.nvim' },
  { 'mason-org/mason-lspconfig.nvim' },
  { 'hrsh7th/cmp-nvim-lsp' },
  { 'hrsh7th/cmp-buffer' },
  { 'hrsh7th/cmp-path' },
  { 'quangnguyen30192/cmp-nvim-tags' },
  { 'hrsh7th/nvim-cmp' },
  { 'L3MON4D3/LuaSnip' },
  { 'saadparwaiz1/cmp_luasnip' },
  { 'nvim-lua/lsp-status.nvim' },
  { 'b0o/SchemaStore.nvim' },

  { 'kylechui/nvim-surround', tag = '*' },
  { 'windwp/nvim-autopairs' },
  { 'numToStr/Comment.nvim' },
  { 'mcauley-penney/tidy.nvim' },

  { 'nvim-treesitter/nvim-treesitter' },
  { 'RRethy/nvim-treesitter-endwise' },
  { 'windwp/nvim-ts-autotag' },
  { 'JoosepAlviste/nvim-ts-context-commentstring' },
  { 'martinda/Jenkinsfile-vim-syntax' },
  { 'aklt/plantuml-syntax' },

  { 'github/copilot.vim' },
  { 'olimorris/codecompanion.nvim' },
  { 'kdheepak/lazygit.nvim' },
  { 'lewis6991/gitsigns.nvim' },
  { 'sindrets/diffview.nvim' },
  { 'will133/vim-dirdiff' },

  { 'marko-cerovac/material.nvim' },
  { 'nvimdev/indentmini.nvim' },
  { 'goolord/alpha-nvim' },
}
